### ISSUE TITLE
小縮尺時のポリゴンが四角くなる

### ISSUE THREAD

**Issue by wata909** [wata909/NationalForest08_mvt#1]
![2020-07-21 09_15_01-国有林小班図（茨城県・テスト）](https://user-images.githubusercontent.com/3130494/87998364-9e213080-cb32-11ea-80f3-750190ebba14.png)

上のように、小縮尺時のポリゴンが四角くなる。

まず、

- サイズが大きいのか
- ポリゴンの数が多いのか

を確認する必要がある。その上で、対策としては

- てぃぴかぬーのオプションで頑張る
- ポリゴンをディゾルブ
- ポリゴンを簡素化
   - 簡素化はQGIS、GRASS、PostGIS ?

を考える

**Comment by smellman** [comment]
--simplify-only-low-zooms で少縮尺の時にsimplifyされちゃうので、 --no-line-simplification で少縮尺でもsimplifyしないか、 --coalesce でまとめちゃうとか？

**Comment by shibamon** [comment]
・ファイルサイズとのバランスを取りたい場合、この結果はTippecanoeが出したひとつの答えです。
・ファイルサイズが大きくなってもいいからオリジナルを保ちたい場合のアプローチとしては
Tippecanoeのオプション

-pf -pk -ps

を付けます。
このオプションは最大ズームにしか利かないので、ズームレベル毎にTippecanoeして全部のズームレベルに利かせます。
きれいになりますがもちろんファイルサイズは大きくなります。
個人的にはTippecanoeの「勝手な間引き」を信用してないので、地物を事前に選別した上でこのアプローチを多用しています。

・総描の提案としては、小縮尺の役割はカバー範囲図であると捉えて、隣接するポリゴンを属性無視で統合するのはいかがでしょう。
私は使ったことないのですが、-aN オプションが使えそうです。

**Comment by hfu** [comment]
@shibamon と同じ考えです。Tippecanoe に無理をさせずに、データを縮尺相応なものにしていくのがよいと思います。

本格的かつシステマティック（バッチ処理可能）にするのであれば、入力する GeoJSON Text Sequence の Feature に tippecanoe 拡張、例えば `tippecanoe: {minzoom: 10, maxzoom: 12, layer: 'han'}`、を入れて細かく制御すると良いかもしれません。

-aN オプションは私も使ったことがないので、勉強してみたいと思います。

**Comment by wata909** [comment]
みなさま、コメントありがとうございますm(__)m

正攻法は、縮尺にあったものを作ることだと思います。とはいえ、できるだけ手間をかけずにということでいくつかオプションを試してみました。基本的には、

`tippecanoe --output-to-directory=no-line-simplification --layer=nationalforest -R 8/227/100 --maximum-zoom=8 --minimum-zoom=8 --no-tile-compression A45-19_08.geojson`

を基に、色々とオプションを試してみました。

no-line-simplification
https://github.com/wata909/NationalForest08_mvt/blob/gh-pages/no-line-simplification/8/227/100.pbf

--coalesce
https://github.com/wata909/NationalForest08_mvt/blob/gh-pages/coalesce/8/227/100.pbf

-pf -pk -ps
https://github.com/wata909/NationalForest08_mvt/blob/gh-pages/pf-pk-ps/8/227/100.pbf

-ps -an
https://github.com/wata909/NationalForest08_mvt/blob/gh-pages/ps-an/8/227/100.pbf

見た感じは、-ps -an で、おおむね希望通りのものが出るかなと思いました。
まずは、これでやってみます！

＃ただ、筆ポリゴンだと、うまくいかないかな…？

**Comment by hfu** [comment]
役割分担、ということで、正攻法に向けてディゾルブを試してみています。
https://github.com/optgeo/hk

具体的には、[Rakefile](https://github.com/optgeo/hk/blob/0ff06099b35dd2ca7c650f6f8908e929a2639ec9/Rakefile#L5) にあるように、
```zsh
ogr2ogr -a_srs 'EPSG:4326' -lco RFC7946=YES -f GeoJSON #{key}.geojson ~/Downloads/#{key}_GML/#{key}.shp -dialect sqlite -sql 'SELECT ST_Union(Geometry) from \"#{key}\"'
```
をやって、全ポリゴンをディゾルブします。相当時間がかかるようです。

データが小さいということで、[神奈川県](https://github.com/optgeo/hk/blob/master/A45-19_14.geojson)をやってみたところです。青森は数時間で終わっていたようですが、北海道は５時間かけてまだ終了しないようです。

北海道がうまく変換できることを確認するまではやってみようと思っています。

**Comment by hfu** [comment]
北から下げていくのとは別に、関東を進めてみようと思いまして、[茨城県](https://github.com/optgeo/hk/blob/master/A45-19_08.geojson)あたりからシステマティックに処理していきます。

もう少しやってみて、全国うまくいきそうであれば、小縮尺全国まとめたベクトルタイルを試作してみようとおもいます。

**Comment by hfu** [comment]
ken_all.geojson を作る Rake タスクを設定し、（１）北海道の変換、（２）東北を南北から挟む変換、（３）順当に東から西に進む変換の３つのプロセスを並行させながら作業を進めています。
継続の作業は、本日の夜以降になりそうです。

https://github.com/optgeo/hk/blob/master/ken_all.geojson

**Comment by wata909** [comment]
@hfu ありがとうございます。ogr2ogrのディゾルブは遅い印象があるので、OpenJUMPで北海道のディゾルブをやろうとしたら、こけてしまいました（汗

林班図の場合はポリゴンのサイズにヴァリエーションがあるので、-ps -an でも上手くいったかもしれません。筆ポリゴンの場合は、比較的サイズがそろっていると思うので、また違うとおもいます。
色々、試してみます

**Comment by hfu** [comment]
@wata909 はい、確かに ogr2ogr のディゾルブは遅かったです。北海道については、時間ほどかかりました。時間はかかりましたがディゾルブができたので、https://github.com/optgeo/hk/blob/master/A45-19_01.geojson に置きました。

全国分のディゾルブができたので、せっかくだからタイルにしてみます。

**Comment by hfu** [comment]
「正攻法」のタイル生産を完了し、テストサイトを立ち上げました🔥
https://optgeo.github.io/hk
